### ISSUE TITLE
Script vbs or JavaScript?

### ISSUE THREAD

**Issue by acquleo** [tksh164/wsfc-generic-script-sample#1]
Hi, I'd like to ask you a question. 
I've implemented resource script in vbs and I thought it was the only supported language. 
Is it also working with JavaScript? 
Thanks

**Comment by tksh164** [comment]
Hi @acquleo, yes, you can implement a script for generic script resource with VBScript or [JScript](https://learn.microsoft.com/en-us/previous-versions/hbxc2t98(v=vs.85)). Actually, [the script that hosting in this repository](https://github.com/tksh164/wsfc-generic-script-sample/blob/master/GenericScript.js) is implemented by JScript. You can try that script in your lab.

**Comment by acquleo** [comment]
Good to know. 
I'll try it next time. 
Thanks
